### ISSUE TITLE
in some cases we should use fetchTarball

### ISSUE THREAD

**Issue by teto** [nix-community/luarocks-nix#13]
`gen_src_from_basic_url` either uses fetchurl or fetchgit but seems like it fails with zip files such as 
```
  src = fetchurl {
    url    = "http://lua.sqlite.org/index.cgi/zip/lsqlite3_fsl09y.zip?uuid=fsl_9y";
    sha256 = "0648hhj7ivqlpqr6402xnxg57xvvi3f28ch5l81hvnka0n4qsjbj";
  };
 ```
first seen in https://github.com/NixOS/nixpkgs/pull/185719#issuecomment-1209068274

cc @scoder12

**Comment by Scoder12** [comment]
Should also use `fetchFromGitHub` if possible

**Comment by Scoder12** [comment]
Actually `fetchFromGitHub` isn't worth the effort if we need to `fetchSubmodules`
