### ISSUE TITLE
luarocks nix generates code with issues

### ISSUE THREAD

**Issue by CloudyChris** [nix-community/luarocks-nix#35]
- **Platform:**
   `Linux (NixOS)`

- **LuaRocks version:**
  `2023-10-19` (installed from nixpkgs, stateVersion `23.11`)

- **Description:**
  Using `pkgs.callPackage` on the output from `luarocks nix` resulted in a failed evaluation. Something about a missing argument to call `buildLuarocksPackage`. Try as I might, I could not find any info on the arguments except the function implementation in `pkgs/development/interpreters/lua-5/build-luarocks-package.nix` which does not specify which arguments are required. Please help

- **Error:**
 Using the output from `luarocks nix` with `pkgs.callPackage` generates the following error
  ```nix
  error: evaluation aborted with the following error message: 'Function called without required argument "buildLuarocksPackage" at /nix/store/hij1mf7y93nzqchcgqsxk38mhwagdcz6-source/pkgs/luarocks-pkgs/pulseaudio_dbus.nix:2'
  ```

- **Configuration file:**
 This is the generated nix code from `luarocks nix pulseaudio_dbus`
 ```nix
{
  buildLuarocksPackage,
  dbus_proxy,
  fetchgit,
  fetchurl,
  lua,
  luaOlder,
}:
buildLuarocksPackage {
  pname = "pulseaudio_dbus";
  version = "0.12.0-2";
  knownRockspec =
    (fetchurl {
      url = "mirror://luarocks/pulseaudio_dbus-0.12.0-2.rockspec";
      sha256 = "050s5819q7v9fs28xrgvpl82pzajvs9sm317nrn0qi018yq64pyv";
    })
    .outPath;
  src = fetchgit (removeAttrs (builtins.fromJSON ''    {
      "url": "https://github.com/stefano-m/lua-pulseaudio_dbus",
      "rev": "b0f6774870658c2f776af6ad4596037f2f60191e",
      "date": "2017-11-11T17:48:42+00:00",
      "path": "/nix/store/38g57wg31hgl29lz4za3csqhqbk4f67a-lua-pulseaudio_dbus",
      "sha256": "1l4nalziwmy3d7sb4jij2d1cml5ghzkg8cwj25v82brj36v3kqd7",
      "hash": "sha256-p+E5thkyL4F2EZIz9OaHr9DKQhMySrL0acNXHj9VltA=",
      "fetchLFS": false,
      "fetchSubmodules": true,
      "deepClone": false,
      "leaveDotGit": false
    }
  '') ["date" "path" "sha256"]);

  disabled = luaOlder "5.1";
  propagatedBuildInputs = [dbus_proxy lua];

  meta = {
    homepage = "https://github.com/stefano-m/lua-pulseaudio_dbus";
    description = "Control PulseAudio devices using DBus";
    license.fullName = "Apache v2.0";
  };
}
 ```

I'd be really grateful for some help. I need pulseaudio_dbus for my awesomeWM config, and it's not in nixpkgs

**Comment by teto** [comment]
I think you are missing the `{}` at the end of the call aka `callPackage (<GENERATED_CODE>) { /* possible overrides, usually empty */}`. Check how it's used at pkgs/development/lua-modules/generated-packages.nix. The README could be updated to mention that. 

Good luck with the packaging.

**Comment by CloudyChris** [comment]
> I think you are missing the `{}` at the end of the call aka `callPackage (<GENERATED_CODE>) { /* possible overrides, usually empty */}`. Check how it's used at pkgs/development/lua-modules/generated-packages.nix. The README could be updated to mention that.
> 
> Good luck with the packaging.

Sorry for the late reply, life happened... it was indeed an issue in the file where I called `callPackage` although not what you suggested. I reported the mistake there to the relevant repository, as the file itself was part of a starter template.
