### ISSUE TITLE
Upstream URLs are seemingly randomized

### ISSUE THREAD

**Issue by abbradar** [nix-community/luarocks-nix#5]
As seen in https://github.com/NixOS/nixpkgs/pull/68158 calling `update-luarocks-packages` picks random upstream URL, so each update touches unrelated packages.

**Comment by teto** [comment]
thanks for the notification, I think I should restrict the available mirrors to prevent unstable urls.
I also might bump luarocks-nix depending on https://github.com/NixOS/nixpkgs/pull/68201

**Comment by teto** [comment]
this should be fixed https://github.com/NixOS/nixpkgs/pull/68258 . It adds mirror support to nixpkgs too \o/
