### ISSUE TITLE
transfer repo to nix-community

### ISSUE THREAD

**Issue by teto** [nix-community/luarocks-nix#6]
according to https://nix-community.github.io/#org-owners, I should ping some members from the list.
So @zimbatm @worldofpeace Iwould like to transfer this repo to nix-community (while keeping commits right). Is that ok/fine ?
under what name ? lua2nix ? luarocks2nix ? luarocks-nix

**Comment by worldofpeace** [comment]
I think `luarocks-nix` sounds sensible. I'd say the name is up to you, though from the readme I did struggle to figure out how it was nix related. But that's nothing we can't fix once it's in nix-community.

>  (while keeping commits right).

Everyone will for sure have admin access to the project they maintain.

> according to https://nix-community.github.io/#org-owners, I should ping some members from the list.

That does sound correct, but It doesn't seem I can invite you into the org,
It seems that's limited to the owners which don't seem to be information someone who isn't a member can access. We should probably add an induction process to https://nix-community.github.io/ to clear this up.

**Comment by teto** [comment]
luarocks-nix converts lua rockspec https://luarocks.org/manifests/openresty/lua-cjson-2.1.0.6-1.rockspec into a nix derivation. That's the program used to generate https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/lua-modules/generated-packages.nix . 
I could add a README if needed.

**Comment by adisbladis** [comment]
Repo is now moved to nix-community :)

**Comment by zimbatm** [comment]
welcome @teto ! :tada:
