### ISSUE TITLE
Provide an option to generate callPackage-compatible code?

### ISSUE THREAD

**Issue by Gabriel439** [nix-community/luarocks-nix#9]
`luarocks nix` generates Nix code that is not compatible with the `callPackage` idiom for Nixpkgs

For example, if I run

```bash
$ luarocks nix inspect
```

… then I get:

```nix
buildLuarocksPackage {
  pname = "inspect";
  version = "3.1.1-0";

  src = fetchurl {
    url    = "https://luarocks.org/inspect-3.1.1-0.src.rock";
    sha256 = "0k4g9ahql83l4r2bykfs6sacf9l1wdpisav2i0z55fyfcdv387za";
  };
  disabled = (luaOlder "5.1");
  propagatedBuildInputs = [ lua ];

  meta = with lib; {
    homepage = "https://github.com/kikito/inspect.lua";
    description = "Lua table visualizer, ideal for debugging";
    license.fullName = "MIT <http://opensource.org/licenses/MIT>";
  };
};
```

… but I was expecting to get something more like:

```nix
{ buildLuarocksPackage
, lib
, fetchurl
, luaOlder
, lua
}:

buildLuarocksPackage {
  pname = "inspect";
  version = "3.1.1-0";

  src = fetchurl {
    url    = "https://luarocks.org/inspect-3.1.1-0.src.rock";
    sha256 = "0k4g9ahql83l4r2bykfs6sacf9l1wdpisav2i0z55fyfcdv387za";
  };
  disabled = (luaOlder "5.1");
  propagatedBuildInputs = [ lua ];

  meta = with lib; {
    homepage = "https://github.com/kikito/inspect.lua";
    description = "Lua table visualizer, ideal for debugging";
    license.fullName = "MIT <http://opensource.org/licenses/MIT>";
  };
}
```

… so that the generated expression could be passed directly to `callPackage`.

My understanding is that the intention behind the current luarocks-nix behavior is to generate code that could be pasted into `lua-modules/generated-packages.nix` (where everything you need is already in scope), but it would be nice if each package could be split into a separate file (sort of like how Python is packaged in Nixpkgs).

One reason for doing this is that it makes it easier to override the Lua package set in a local overlay (e.g. using `overrides`).  In such an overlay, typically the dependencies you need are not in scope like they are in the `generated-packages.nix` file.

Would it be possible to provide an option to generate code that generates a self-contained Nix expression that is compatible with `callPackage`?

**Comment by teto** [comment]
I've merged the mentioned PR. If you want to implement this, you should base your work on the test-speedup branch (this repo is a bit of a mess sry). I dont think this needs to be a new command, just make it the default. But then make sure pkgs/development/lua-modules/generated-packages.nix keeps working.

**Comment by teto** [comment]
the version in branch https://github.com/nix-community/luarocks-nix/tree/standalone does just that. I need to fix a few issues on nixpkgs side before merging though

**Comment by teto** [comment]
merged now. closing this.
